name: CDK Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install AWS CDK
        run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE_ARN}}
          aws-region: ap-northeast-1
      - name: CDK Diff
        if: contains(github.event_name, 'pull_request')
        run: npm run cdk -- diff
      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: npm run cdk -- deploy --require-approval never
